In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import cv2
from numba import njit
from einops import rearrange
import torch
import torch.nn as nn
from einops import rearrange

In [22]:
EMBEDDING_DIM = 4
NUM_HEADS = 1

mAttn = nn.Linear(EMBEDDING_DIM, EMBEDDING_DIM*NUM_HEADS*3)

In [23]:
x = torch.randn(3, 2, 4)

In [24]:
x = mAttn(x).chunk(3, dim=-1)

In [25]:
x[0].shape

torch.Size([3, 2, 4])

In [26]:
q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = NUM_HEADS), x)

In [27]:
q.shape, k.shape, v.shape

(torch.Size([3, 1, 2, 4]), torch.Size([3, 1, 2, 4]), torch.Size([3, 1, 2, 4]))

In [32]:
dots = torch.einsum('bhid, bhjd -> bhij', q, k)

In [33]:
dots.shape

torch.Size([3, 1, 2, 2])

In [165]:
q = torch.randn(2,4) #queries
k = torch.randn(2,4) #keys
v = torch.randn(2,4) #values

q,k

(tensor([[ 0.8499, -1.6322,  0.7599,  0.5016],
         [ 0.6634,  0.2268, -1.6986, -0.1436]]),
 tensor([[ 0.8884,  0.8738, -1.7937, -0.5460],
         [-1.6524,  0.1882, -0.2510,  0.6634]]))

In [166]:
a = q.unsqueeze(0) - k.unsqueeze(1)

In [168]:
a

tensor([[[-0.0385, -2.5060,  2.5536,  1.0476],
         [-0.2250, -0.6470,  0.0950,  0.4025]],

        [[ 2.5022, -1.8205,  1.0109, -0.1618],
         [ 2.3158,  0.0386, -1.4477, -0.8069]]])

In [169]:
v

tensor([[-0.1861, -0.7602, -1.1181, -0.0934],
        [ 0.5607, -1.2499,  2.5698, -2.3461]])

In [170]:
a * v.unsqueeze(1)

tensor([[[ 0.0072,  1.9050, -2.8550, -0.0979],
         [ 0.0419,  0.4918, -0.1062, -0.0376]],

        [[ 1.4030,  2.2754,  2.5977,  0.3795],
         [ 1.2985, -0.0482, -3.7203,  1.8932]]])

In [173]:
a[1] * v[1]

tensor([[ 1.4030,  2.2754,  2.5977,  0.3795],
        [ 1.2985, -0.0482, -3.7203,  1.8932]])

In [1]:
16*16

256