In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [11]:
img = np.ones(25)
img[:15] = 0
np.random.shuffle(img)
img = img.reshape((5,5))
img

array([[1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [12]:
preds = np.ones(25)
preds[:10] = 0
np.random.shuffle(preds)
preds = preds.reshape((5,5))
preds

array([[1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
intersection = (preds.reshape(-1) * img.reshape(-1)).sum()
dice_loss = (2 * intersection) / (preds.sum() + img.sum())

In [14]:
dice_loss

0.56

In [16]:
(preds.reshape(-1) == img.reshape(-1)).sum() / 25 * 100

56.00000000000001

In [22]:
x = np.arange(8).reshape((2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
x.transpose(2,0,1)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])